name: 'Tencent COS and CDN'
description: 'Deploy files to tencent cloud COS and flush CDN cache'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  secret_id:
    description: 'Tencent cloud secret id. Should be referred to a encrypted environment variable'
    required: true
  secret_key:
    description: 'Tencent cloud secret key. Should be referred to a encrypted environment variable'
    required: true
  session_token:
    description: 'Tencent cloud sessionToken for temporary secret, may get from other actions'
    required: false
  cos_bucket:
    description: 'COS bucket name'
    required: true
  cos_region:
    description: 'COS bucket region'
    required: true
  cos_accelerate:
    description: 'Set to true for using accelerate domain to upload files. Default is false'
    required: false
  cos_init_options:
    description: 'Other options for init COS SDK instance operator'
    required: false
  cos_put_options:
    description: 'Other options for putObject operator'
    required: false
  cos_replace_file:
    description: 'Whether to replace the existing file. Default is true'
    required: false
  cos_file_check_concurrent:
    description: 'Check whether the file needs to be uploaded concurrently'
    required: false
  cdn_type:
    description: 'CDN type, cdn or eo. Default is cdn'
    required: false
  cdn_prefix:
    description: 'CDN url prefix if you are using Tencent Cloud CDN. Default is empty'
    required: false
  cdn_wait_flush:
    description: 'Whether to wait for CDN refresh to complete. Defaults is false'
    required: false
  eo_zone:
    description: 'EO zone ID if you are using Tencent Cloud EdgeOne CDN. Default is empty'
    required: false
  local_path:
    description: 'Local path to be uploaded to COS. Directory or file is allowed'
    required: true
  remote_path:
    description: 'COS path to put the local files in on COS'
    required: false
  clean:
    description: 'Set to true for cleaning files on COS path which are not existed in local path. Default is false'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'